# Generated by Django 6.0.2 on 2026-03-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_catagory_id_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
    ]
