# Generated by Django 6.0.2 on 2026-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_product_reorder_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbalance',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
    ]
