# Generated by Django 6.0.2 on 2026-03-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='stockbalance',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stockbalance',
            old_name='Warehouse_id',
            new_name='warehouse',
        ),
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='Warehouse_id',
            new_name='warehouse',
        ),
        migrations.AlterUniqueTogether(
            name='stockbalance',
            unique_together={('product', 'warehouse')},
        ),
    ]
