# Generated by Django 6.0.2 on 2026-03-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_remove_stockbalance_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_auto_reorder',
            field=models.BooleanField(default=False),
        ),
    ]
